### ISSUE TITLE
Read me misleading?

### ISSUE THREAD

**Issue by leegee** [marcodejongh/chai-webdriverio#35]
Ran the code from the readme:

```
// Start with a webdriver instance:
var sw = require('selenium-webdriver');
var driver = new sw.Builder()
  .withCapabilities(sw.Capabilities.chrome())
  .build()

// And then...
var chai = require('chai');
var chaiWebdriver = require('chai-webdriver');
chai.use(chaiWebdriver(driver));

// And you're good to go!
driver.get('http://github.com');
chai.expect('#site-container h1.heading').dom.to.not.contain.text("I'm a kitty!");
```

Got this:

```
TypeError: checkSizzleExists(...).then(...).then(...).thenCatch is not a function
    at finder (C:\Users\User\AppData\Roaming\npm\node_modules\chai-webdriver\node_modules\webdriver-sizzle\lib\webdriver_sizzle.js:60:10)
    at call (C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\webdriver.js:1066:28)
    at C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\webdriver.js:907:19
    at ManagedPromise.invokeCallback_ (C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\promise.js:1384:14)
    at TaskQueue.execute_ (C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\promise.js:3092:14)
    at TaskQueue.executeNext_ (C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\promise.js:3075:27)
    at asyncRun (C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\promise.js:2982:25)
    at C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\promise.js:676:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.call(function)
    at thenableWebDriverProxy.call (C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\webdriver.js:901:23)
    at thenableWebDriverProxy.findElementsInternal_ (C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\webdriver.js:1066:17)
    at thenableWebDriverProxy.findElements (C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\webdriver.js:1043:19)
    at Function.one.all (C:\Users\User\AppData\Roaming\npm\node_modules\chai-webdriver\node_modules\webdriver-sizzle\lib\webdriver_sizzle.js:64:19)
    at assertElementExists (C:\Users\User\AppData\Roaming\npm\node_modules\chai-webdriver\lib\index.js:18:16)
    at Proxy.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\chai-webdriver\lib\index.js:90:14)
    at Proxy.methodWrapper (C:\Users\User\AppData\Roaming\npm\node_modules\chai\lib\chai\utils\addMethod.js:57:25)
    at Object.<anonymous> (C:\Users\User\src\izel\tests\chai.js.old:17:62)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)

C:\Users\User\src\izel (master)
```

**Comment by mltsy** [comment]
It looks like this is actually about `chai-webdriver` not `chai-webdriverio` (confusing, I know).  Or are you trying to use webdriverio?

**Comment by leegee** [comment]
Chai webdriver seems to be using this webdriver, or am I misreading?

In any case, I closed the ticket, I thought, as it was all my foolish error!

**Comment by mltsy** [comment]
Oh, nope it's still open!  But I'll close it for you :wink:

Just to clarify, the original `chai-webdriver` package (from which this package is inspired) is a library for using [chai](https://www.npmjs.com/package/chai) with special assertions pertaining to [selenium-webdriver](https://www.npmjs.com/package/selenium-webdriver).

This package (`chai-webdriverio`) is the same thing, but with special assertions pertaining to [webdriverio](https://www.npmjs.com/package/webdriverio).

**Comment by leegee** [comment]
Sure, but my reading of the chai-webdriver package is that it using this
webdriver package, to which it adds chai ?

Hope I've not opened the ticket again!

Thank you very much!

**Comment by mltsy** [comment]
Hmm... the issue you are commenting on right now is in the repository for a package called `chai-webdriverio`, which neither uses, nor is used by `chai-webdriver` as far as I know.  Do you see something that indicates otherwise?

**Comment by leegee** [comment]
Oh, drat!  Sorry - past midnight here, should have read the mail more
carefully!  Sorry.
